---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: build llvm libraries
    init: |
      pushd build-scripts || exit 1
      python3 ./build_llvm.py || exit 1
      popd

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

vscode:
  extensions:
    # - dtsvet.vscode-wasm
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/dtsvet/vsextensions/vscode-wasm/1.3.1/vspackage
    # - ms-vscode.cpptools
    - https://github.com/microsoft/vscode-cpptools/releases/download/1.6.0/cpptools-linux.vsix
    # ms-python.vscode-pylance
    - https://github.com/microsoft/vscode-python/releases/download/2021.9.1218897484/ms-python-release.vsix
    - redhat.vscode-yaml
    - vadimcn.vscode-lldb	
    - vscodevim.vim
